### ISSUE TITLE
Unable to run code after cloning

### ISSUE THREAD

**Issue by shahankit783** [qualityshepherd/protractor-example#8]
I have cloned code and try to run from my end but getting below error:
E/configParser - Error: Cannot find module 'babel-register'
    at Function.Module._resolveFilename (module.js:538:15)
    at Function.Module._load (module.js:468:25)
    at Module.require (module.js:587:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/Users/test/protractor_example/conf.js:2:1)
    at Module._compile (module.js:643:30)
    at Object.Module._extensions..js (module.js:654:10)
    at Module.load (module.js:556:32)
    at tryModuleLoad (module.js:499:12)
    at Function.Module._load (module.js:491:3)

Can you please upload latest working code.. Thanks a lot!!

PS: My node version is 8.9.4 and running in mac environment

**Comment by qualityshepherd** [comment]
Did u run npm install?

**Comment by shahankit783** [comment]
yes I did

**Comment by qualityshepherd** [comment]
I'm not able to reproduce this, so it's hard to debug. Definitely feels like a babel issue... do you have babel installed globally?

**Comment by shahankit783** [comment]
No but i somehow managed to run it. Thank you for your help.  I am closing this issue

**Comment by qualityshepherd** [comment]
It was likely an npm hiccup. Sorry for the trouble...
